# Generated by Django 3.1.7 on 2021-04-05 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowRequest',
            new_name='FriendRequest',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
